title       = "mempool"
baseURL     = "https://mempool-cli.tamnd.com/"
description = "A command line for Mempool.space Bitcoin data."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mempool-cli"
